### ISSUE TITLE
Verify all endpoints and make sure output is consistent with Agora, document where it's different

### ISSUE THREAD

**Issue by beeman** [kin-labs/kinetic#121]

**Comment by RamirezAlex** [comment]
At this point, all of the methods are different from Agora, mostly because we now include the mint for all the operations, but also because we include some that don't exist in Agora such as: getExplorerUrl.

There is also the case where the `mergeTokenAccounts` has not been implemented yet in Kinetic, which should be fix with #204. Some methods have a different name now.

https://docs.google.com/spreadsheets/d/1SgfIaSb12r9Wz7v6DBjN1BvkVhtibKYKnW0Nzm744lY/
