### ISSUE TITLE
Upgrade dependencies and enable Dependabot

### ISSUE THREAD

**Issue by RamirezAlex** [kin-labs/kinetic#307]
We currently spend time upgrading and maintaining out dependency tree. We want to automate this.

- [ ] Upgrade all dependencies `yarn upgrade-interactive --latest`  is a good tool for this.
- [ ] Fix any breaking issues until the current dependencies are up to date.
- [ ] Enable [Dependabot](https://github.com/dependabot).

**Comment by beeman** [comment]
As explained here, I'd rather not use automated deps updates as in my experience it's doing more harm than good. Especially because it doesn't understand nx and migrations we will be left with a broken monorepo at some point because Nx migrations have not been run.

https://github.com/kin-labs/kinetic/pull/306#issuecomment-1168682529

Instead, I am happy to take on maintenance of updates until further notice
