### ISSUE TITLE
Environments can not have a dash (-) in their name

### ISSUE THREAD

**Issue by mocolicious** [kin-labs/kinetic#551]
Some of the apps created in our test environment running RC13 are unable to access the toolbox tab and it just spins until it fails.  The workaround we found was to delete and recreate the app environment.   Reach out to us on Discord and I can grant temporary access to our test server to observe the issue.

**Comment by beeman** [comment]
After looking into this it turned out that the issue has to do with environment names that have a dash in them (like `my-devnet`).

For now, the recommended fix is to use short names with no dash (generally seems like a good idea) while we fork on a fix.

# Todo

- [ ] Add test case that adds a failing environment, make sure it breaks the test
- [ ] Fix the failing test, making sure it works.
